name: Auto Commit & Push

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Git config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
      - name: Auto Commit & Push
        run: |
          git add .
          git commit -m "Automated commit" || exit 0 # Avoids errors if no changes
          git push
